-- Voxa Database Schema
-- Migration: 001_initial_schema
-- Description: Creates initial tables for meetings, TTS messages, and user settings

-- Enable UUID extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Meetings table
-- Stores meeting information linked to users
CREATE TABLE IF NOT EXISTS meetings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL, -- References Supabase auth.users(id)
  title VARCHAR(255) NOT NULL,
  platform VARCHAR(50) NOT NULL, -- 'google-meet', 'zoom', 'microsoft-teams'
  scheduled_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  duration INTEGER, -- Duration in seconds
  status VARCHAR(20) NOT NULL DEFAULT 'scheduled', -- 'scheduled', 'active', 'completed', 'cancelled'
  meeting_url TEXT,
  language VARCHAR(10) DEFAULT 'en-US', -- Meeting language preference
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  CONSTRAINT meetings_status_check CHECK (status IN ('scheduled', 'active', 'completed', 'cancelled')),
  CONSTRAINT meetings_platform_check CHECK (platform IN ('google-meet', 'zoom', 'microsoft-teams', 'other'))
);

-- TTS Messages table
-- Stores all text-to-speech messages generated by users
CREATE TABLE IF NOT EXISTS tts_messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL, -- References Supabase auth.users(id)
  meeting_id UUID REFERENCES meetings(id) ON DELETE SET NULL, -- Optional: link to meeting
  text_input TEXT NOT NULL,
  text_length INTEGER NOT NULL,
  voice_used VARCHAR(20) NOT NULL DEFAULT 'alloy', -- 'alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'
  language VARCHAR(10), -- Language code (e.g., 'en-US')
  speed DECIMAL(3,1) DEFAULT 1.0, -- Speed multiplier (0.5 to 2.0)
  pitch DECIMAL(3,1) DEFAULT 1.0, -- Pitch multiplier (0.5 to 2.0)
  status VARCHAR(20) NOT NULL DEFAULT 'pending', -- 'pending', 'sent', 'failed'
  error_message TEXT, -- Error details if status is 'failed'
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  CONSTRAINT tts_messages_status_check CHECK (status IN ('pending', 'sent', 'failed')),
  CONSTRAINT tts_messages_voice_check CHECK (voice_used IN ('alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer')),
  CONSTRAINT tts_messages_speed_check CHECK (speed >= 0.5 AND speed <= 2.0),
  CONSTRAINT tts_messages_pitch_check CHECK (pitch >= 0.5 AND pitch <= 2.0),
  CONSTRAINT tts_messages_text_length_check CHECK (text_length > 0 AND text_length <= 500)
);

-- User Settings table
-- Stores user preferences for TTS and application settings
CREATE TABLE IF NOT EXISTS user_settings (
  user_id UUID PRIMARY KEY, -- References Supabase auth.users(id)
  preferred_voice VARCHAR(20) NOT NULL DEFAULT 'alloy',
  default_speed DECIMAL(3,1) NOT NULL DEFAULT 1.0,
  default_pitch DECIMAL(3,1) NOT NULL DEFAULT 1.0,
  default_language VARCHAR(10) NOT NULL DEFAULT 'en-US',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  CONSTRAINT user_settings_voice_check CHECK (preferred_voice IN ('alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer')),
  CONSTRAINT user_settings_speed_check CHECK (default_speed >= 0.5 AND default_speed <= 2.0),
  CONSTRAINT user_settings_pitch_check CHECK (default_pitch >= 0.5 AND default_pitch <= 2.0)
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_meetings_user_id ON meetings(user_id);
CREATE INDEX IF NOT EXISTS idx_meetings_status ON meetings(status);
CREATE INDEX IF NOT EXISTS idx_meetings_scheduled_at ON meetings(scheduled_at);
CREATE INDEX IF NOT EXISTS idx_meetings_created_at ON meetings(created_at);

CREATE INDEX IF NOT EXISTS idx_tts_messages_user_id ON tts_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_tts_messages_meeting_id ON tts_messages(meeting_id);
CREATE INDEX IF NOT EXISTS idx_tts_messages_status ON tts_messages(status);
CREATE INDEX IF NOT EXISTS idx_tts_messages_created_at ON tts_messages(created_at);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers to automatically update updated_at
CREATE TRIGGER update_meetings_updated_at
  BEFORE UPDATE ON meetings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_settings_updated_at
  BEFORE UPDATE ON user_settings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE meetings IS 'Stores meeting information and metadata';
COMMENT ON TABLE tts_messages IS 'Stores all text-to-speech messages generated by users';
COMMENT ON TABLE user_settings IS 'Stores user preferences for TTS and application settings';

COMMENT ON COLUMN meetings.user_id IS 'References Supabase auth.users(id) - the user who owns this meeting';
COMMENT ON COLUMN tts_messages.user_id IS 'References Supabase auth.users(id) - the user who generated this TTS message';
COMMENT ON COLUMN tts_messages.meeting_id IS 'Optional reference to a meeting where this TTS was used';
COMMENT ON COLUMN tts_messages.text_length IS 'Character count of text_input (max 500)';
